Use https for cldf.clld.org urls
cldf/cldf pull request #147
Opened 2023-11-01 18:13 UTC by ar-jan

Fixes browser scrolling to url fragments.

2023-11-01 18:16 UTC, ar-jan commented
Oh wait, I guess this may not be correct for schema URLs. But would be helpful for documentation links.

2023-11-05 11:28 UTC, xrotwang commented
Yes, for better or worse, we are stuck with the term URIs using the `http` scheme.

2023-11-06 12:24 UTC, ar-jan commented
I've now omitted the schema URLs from the replacement.

2023-11-06 12:58 UTC, xrotwang requested changes
Basically, only the property URLs which are used as link targets for a **labeled** link might be changed to `https`. And even then, I could imagine people using "copy link" functionality of their browsers intending to get proper property URLs. So overall, I fear this change might introduce more confusion than convenience.

2023-11-06 12:58 UTC, xrotwang commented on README.md
> +  changes. So starting with CLDF 1.1, we will keep `https://cldf.clld.org/v1.0/terms.rdf`
This is the namespace URL and should stay with `http` as well.

2023-11-06 12:58 UTC, xrotwang commented on README.md
> +`propertyUrl` `https://cldf.clld.org/v1.0/terms.rdf#languageReference`
Ontology term. Keep `http`.

2023-11-06 12:58 UTC, xrotwang commented on README.md
> +assuming that the `LanguageTable` component has `url` `languages.csv` and a column `ID` with `propertyUrl` `https://cldf.clld.org/v1.0/terms.rdf#id`.
Ontology term. Keep http.

2023-11-06 12:58 UTC, xrotwang commented on README.md
> +if the referenced column does not have a `propertyUrl` `https://cldf.clld.org/v1.0/terms.rdf#id`.
Ontology term. Keep http.

2023-11-06 12:58 UTC, xrotwang commented on components/codes/README.md
> +key with `propertyUrl` `https://cldf.clld.org/v1.0/terms.rdf#codeReference`.
Ontology term. Keep http.

2023-11-06 12:58 UTC, xrotwang commented on components/codes/description.md
> +key with `propertyUrl` `https://cldf.clld.org/v1.0/terms.rdf#codeReference`.
Ontology term. Keep http.

2023-11-06 12:58 UTC, xrotwang commented on components/cognates/README.md
> +`https://cldf.clld.org/v1.0/terms.rdf#segments` where the secondary separator
Ontology term. Keep http.

2023-11-06 12:58 UTC, xrotwang commented on components/cognates/description.md
> +`https://cldf.clld.org/v1.0/terms.rdf#segments` where the secondary separator
Ontology term. Keep http.

2023-11-06 12:58 UTC, xrotwang commented on components/contributions/description.md
> +Thus, for WALS Online one would add a column with `propertyURL` `https://cldf.clld.org/v1.0/terms.rdf#contributionReference`
Ontology term. Keep http.

2023-11-06 13:23 UTC, ar-jan commented
Oh, I missed the backtick variants. But given this,

> And even then, I could imagine people using "copy link" functionality of their browsers intending to get proper property URLs.

I guess I'd better just leave this alone and close, sorry for the noise.

2023-11-06 13:23 UTC, closed without merging

2023-11-06 13:32 UTC, xrotwang commented
Some noise is appreciated. Now we have something to refer to whenever this discussion comes up again :)